// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6lPuKbb-kxNm_EHr7Mzb6ak36k5RYE9w',
    appId: '1:657046049929:web:6ce7e181cfac7364abe258',
    messagingSenderId: '657046049929',
    projectId: 'chat-app-97875',
    authDomain: 'chat-app-97875.firebaseapp.com',
    storageBucket: 'chat-app-97875.firebasestorage.app',
    measurementId: 'G-9EN45GSGXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG_chZdmDjn9_3-obmam7flgIrNPjkslc',
    appId: '1:657046049929:android:ac1e35d091a73561abe258',
    messagingSenderId: '657046049929',
    projectId: 'chat-app-97875',
    storageBucket: 'chat-app-97875.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeL3lhNLIxFJUR6GkJIk2vQXDwTlc1dCI',
    appId: '1:657046049929:ios:1683c4aa41b24042abe258',
    messagingSenderId: '657046049929',
    projectId: 'chat-app-97875',
    storageBucket: 'chat-app-97875.firebasestorage.app',
    iosBundleId: 'com.example.testAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeL3lhNLIxFJUR6GkJIk2vQXDwTlc1dCI',
    appId: '1:657046049929:ios:1683c4aa41b24042abe258',
    messagingSenderId: '657046049929',
    projectId: 'chat-app-97875',
    storageBucket: 'chat-app-97875.firebasestorage.app',
    iosBundleId: 'com.example.testAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDP1_W4F-jOznYbOq8PKYmlEoV95wdUb8',
    appId: '1:657046049929:web:70a1e49143ac5221abe258',
    messagingSenderId: '657046049929',
    projectId: 'chat-app-97875',
    authDomain: 'chat-app-97875.firebaseapp.com',
    storageBucket: 'chat-app-97875.firebasestorage.app',
    measurementId: 'G-4FY8W5X4B4',
  );
}
